figures:

  - name: nir_flat_inner_order_pix_mean
    type: time_series
    title: NIR Flat Inner Order Pixel Mean
    filename: nir_flat_inner_order_pix_mean.png
    time_range: last_3_months
    y_label: electrons

    series:
      - label: SLIT0.5
        style: markers
        datapoint_query: nir_flat_inner_order_pix_mean_slit05

      - label: SLIT1.0
        style: markers
        datapoint_query: nir_flat_inner_order_pix_mean_slit10

      - label: SLIT1.5
        style: markers
        datapoint_query: nir_flat_inner_order_pix_mean_slit15


  - name: nir_flat_ordexp50
    type: time_series
    title: NIR Flat ORDEXP50
    filename: nir_flat_ordexp50.png
    time_range: last_3_months
    y_label: electrons

    series:
      - label: SLIT0.5
        style: markers
        datapoint_query: nir_flat_orderxp50_slit05

      - label: SLIT1.0
        style: markers
        datapoint_query: nir_flat_orderxp50_slit10

      - label: SLIT1.5
        style: markers
        datapoint_query: nir_flat_orderxp50_slit15


  - name: nir_flat_x_res_sd
    type: time_series
    title: NIR Flat X Residual SD
    filename: nir_flat_x_res_sd.png
    time_range: last_3_months
    y_label: pixels

    series:
      - label: SLIT0.5
        style: markers
        datapoint_query: nir_flat_x_res_sd_slit05

      - label: SLIT1.0
        style: markers
        datapoint_query: nir_flat_x_res_sd_slit10

      - label: SLIT1.5
        style: markers
        datapoint_query: nir_flat_x_res_sd_slit15