figures:

  - name: nir_dark_median
    type: time_series
    title: NIR Dark Median Level
    filename: nir_dark_median.png
    time_range: last_3_months
    y_label: electrons

    series:
      - label: 2 s
        style: markers
        datapoint_query: nir_dark_median_2s

      - label: 5 s
        style: markers
        datapoint_query: nir_dark_median_5s

      - label: 10 s
        style: markers
        datapoint_query: nir_dark_median_10s

      - label: 15 s
        style: markers
        datapoint_query: nir_dark_median_15s

      - label: 60 s
        style: markers
        datapoint_query: nir_dark_median_60s

      - label: 120 s
        style: markers
        datapoint_query: nir_dark_median_120s

      - label: 300 s
        style: markers
        datapoint_query: nir_dark_median_300s

      - label: 600 s
        style: markers
        datapoint_query: nir_dark_median_600s

      - label: 900 s
        style: markers
        datapoint_query: nir_dark_median_900s