figures:

  - name: vis_flat_inner_order_pix_mean
    type: time_series
    title: VIS Flat Inner Order Pixel Mean
    filename: vis_flat_inner_order_pix_mean.png
    time_range: last_3_months
    y_label: electrons

    series:
      - label: SLIT0.5
        style: markers
        datapoint_query: vis_flat_inner_order_pix_mean_slit05

      - label: SLIT1.0
        style: markers
        datapoint_query: vis_flat_inner_order_pix_mean_slit10

      - label: SLIT1.5
        style: markers
        datapoint_query: vis_flat_inner_order_pix_mean_slit15

      - label: SLIT5.0
        style: markers
        datapoint_query: vis_flat_inner_order_pix_mean_slit50


  - name: vis_flat_ordexp50
    type: time_series
    title: VIS Flat ORDEXP50
    filename: vis_flat_ordexp50.png
    time_range: last_3_months
    y_label: electrons

    series:
      - label: SLIT0.5
        style: markers
        datapoint_query: vis_flat_orderxp50_slit05

      - label: SLIT1.0
        style: markers
        datapoint_query: vis_flat_orderxp50_slit10

      - label: SLIT1.5
        style: markers
        datapoint_query: vis_flat_orderxp50_slit15

      - label: SLIT5.0
        style: markers
        datapoint_query: vis_flat_orderxp50_slit50


  - name: vis_flat_x_res_sd
    type: time_series
    title: VIS Flat X Residual SD
    filename: vis_flat_x_res_sd.png
    time_range: last_3_months
    y_label: pixels

    series:
      - label: SLIT0.5
        style: markers
        datapoint_query: vis_flat_x_res_sd_slit05

      - label: SLIT1.0
        style: markers
        datapoint_query: vis_flat_x_res_sd_slit10

      - label: SLIT1.5
        style: markers
        datapoint_query: vis_flat_x_res_sd_slit15

      - label: SLIT5.0
        style: markers
        datapoint_query: vis_flat_x_res_sd_slit50