figures:

  - name: vis_bias_level
    type: time_series
    title: VIS Bias Median Level
    filename: vis_bias_level.png
    time_range: last_3_months
    y_label: ADU

    series:
      - label: SHG
        style: markers
        datapoint_query: vis_bias_median_shg

      - label: FLG
        style: markers
        datapoint_query: vis_bias_median_flg

      - label: SLG
        style: markers
        datapoint_query: vis_bias_median_slg

      - label: FHG
        style: markers
        datapoint_query: vis_bias_median_fhg