figures:

  - name: vis_master_ron
    type: time_series
    title: VIS Master RON
    filename: vis_master_ron.png
    time_range: last_3_months
    y_label: electrons

    series:
      - label: SHG
        style: markers
        datapoint_query: vis_master_ron_shg

      - label: FLG
        style: markers
        datapoint_query: vis_master_ron_flg

      - label: SLG
        style: markers
        datapoint_query: vis_master_ron_slg

      - label: FHG
        style: markers
        datapoint_query: vis_master_ron_fhg