figures:

  - name: vis_master_ron
    type: time_series
    title: VIS Master RON
    filename: vis_master_ron.png
    time_range: last_3_months
    y_label: ADU

    series:
      - label: SHG
        style: markers
        filters:
          soxspipe_recipe: soxs-mbias
          qc_name: MASTER RON
          eso seq arm: VIS
          binning: 1x1
          rospeed: "1"
          qc_order: "-1"

      - label: FLG
        style: markers
        filters:
          soxspipe_recipe: soxs-mbias
          qc_name: MASTER RON
          eso seq arm: VIS
          binning: 1x1
          rospeed: "2"
          qc_order: "-1"

      - label: SLG
        style: markers
        filters:
          soxspipe_recipe: soxs-mbias
          qc_name: MASTER RON
          eso seq arm: VIS
          binning: 1x1
          rospeed: "3"
          qc_order: "-1"

      - label: FHG
        style: markers
        filters:
          soxspipe_recipe: soxs-mbias
          qc_name: MASTER RON
          eso seq arm: VIS
          binning: 1x1
          rospeed: "4"
          qc_order: "-1"