paths:
  # Root folder containing SOXS pipeline reduction data
  qc_root: data/upstream/long_term_reduction/

  # Historical QC database managed by this tool
  qc_database: data/qc.sqlite

acquisition:
  # Name of the upstream SOXS pipeline database inside each session folder
  upstream_database_name: soxspipe.db

  # Upstream table/view to read
  upstream_table: quality_control_plus_lite

plots:
  output_dir: plots
  show: false

  include:
    - plots/datapoint_queries.yaml
    - plots/vis_bias.yaml
    - plots/vis_master_ron.yaml
    - plots/nir_dark.yaml
    - plots/nir_dark_ron.yaml
    - plots/vis_flat.yaml
    - plots/nir_flat.yaml
    - plots/dispersion_solution.yaml
    - plots/efficiency.yaml
    - plots/order_location.yaml
